name: Diary-CI

on:
  push:
    paths:
      - 'DiaryService/**'
  pull_request:
    paths:
      - 'DiaryService/**'

jobs:
  build_and_test:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet publish .\DiaryService\DiaryService\DiaryService.csproj -c Release -o /app/publish

      - name: Lint
        run: dotnet format --verify-no-changes .\DiaryService\

      - name: Test
        run: dotnet test DiaryService
