name: NotificationService-CI

on:
  push:
    paths:
      - 'NotificationService/**'
  pull_request:
    paths:
      - 'NotificationService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cd NotificationService && go build -o notification ./cmd

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: NotificationService

      - name: Test
        run: cd NotificationService && go test ./...
