name: CI

on:
  push:
    paths:
      - 'NotificationService/**'
  pull_request:
    paths:
      - 'NotificationService/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Test
        run: go test ./...

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Let's test it!
