name: CI

on:
  push:
    paths:
      - 'NotificationService/**'
  pull_request:
    paths:
      - 'NotificationService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: NotificationService

      - name: Test
        run: go test NotificationService/...
