name: CI

on:
  push:
    paths:
      - 'NotificationService/**'
  pull_request:
    paths:
      - 'NotificationService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses : actions/checkout@v2

      - name: Lint
        run: cd NotificationService && golangci-lint run

      - name: Test
        run: go test ./...
