name: CI

on:
  push:
    paths:
      - 'NotificationService/**'
  pull_request:
    paths:
      - 'NotificationService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use project dir
        run: cd NotificationService

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: go test ./...
