name: SubscriptionService-CI

on:
  push:
    paths:
      - 'SubscriptionService/**'
  pull_request:
    paths:
      - 'SubscriptionService/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: SubscriptionService

      - name: Test
        run: cd SubscriptionService && go test ./...
