name: User-CI

on:
  push:
    paths:
      - 'UserService/**'
  pull_request:
    paths:
      - 'UserService/**'

jobs:
  test:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test UserService
