name: User-CI

on:
  push:
    paths:
      - 'UserService/**'
  pull_request:
    paths:
      - 'UserService/**'

jobs:
  build_and_test:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet publish .\UserService\UserService\UserService.csproj -c Release -o /app/publish

      - name: Test
        run: dotnet test UserService
